spring.application.name=Taskflow

spring.datasource.url=jdbc:postgresql://localhost:5432/taskflow
spring.datasource.username=postgres
spring.datasource.password=Prince@17

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=taskflowSecretKeyForJwtAuthentication1234567890
jwt.expiration=86400000

spring.data.redis.host=localhost
spring.data.redis.port=6379